import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  ShoppingCartIcon,
  Cog6ToothIcon,
  ClipboardDocumentListIcon,
  ArrowRightOnRectangleIcon,
} from "@heroicons/react/24/outline"; // Import Heroicons

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Flat Navbar */}
        <nav className="p-4 overflow-y-hidden">
          {" "}
          {/*Added border-b for better look*/}
          <div className="container mx-auto flex justify-between items-center">
            <Link href="/" className="font-bold text-xl">
              Vr
            </Link>
            <div className="flex space-x-4 items-center">
              {" "}
              {/*Added items-center*/}
              <NavItem href="/cart" icon={ShoppingCartIcon} label="Cart" />
              <NavItem href="/settings" icon={Cog6ToothIcon} label="Settings" />
              <NavItem
                href="/orders"
                icon={ClipboardDocumentListIcon}
                label="Orders"
              />
              <NavItem
                href="/logout"
                icon={ArrowRightOnRectangleIcon}
                label="Logout"
                onClick={() => {
                  if (window.confirm("Are you sure you want to logout?")) {
                    localStorage.removeItem("token");
                    window.location.href = "/login";
                  }
                }}
              />
            </div>
          </div>
        </nav>
        {/* Content */}
        <main className="min-h-screen overflow-y-hidden">{children}</main>
      </body>
    </html>
  );
}

function NavItem({ href, icon: Icon, label }) {
  const isActive = (pathname) => {
    if (typeof window === "undefined") return false; //check if window is defined to avoid errors during server side rendering
    return window.location.pathname === pathname;
  };
  return (
    <Link
      href={href}
      className={`flex items-center space-x-1 hover:text-gray-600 ${
        isActive(href) ? "text-blue-600 font-semibold" : ""
      }`}
    >
      <Icon className="h-5 w-5" />
      <span>{label}</span>
    </Link>
  );
}
